services:
  bybit_trade_script:
    build:
      context: .
      dockerfile: Dockerfile
    image: bybit_script
    container_name: bybit_script_2
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    volumes:
      - .:/app
      - ./logs:/app_logs
    working_dir: /app
    command: sh -c "python main.py 2>&1 | tee -a /app_logs/script_logs.log"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
    env_file:
      - .env
    networks:
      - db_net

networks:
  db_net:
    external: true

