services:
  bybit-trade_script:
    build:
      context: .
      dockerfile: Dockerfile
    image: bybit_tp_sl_04_03_25
    container_name: bybit_tp_sl_04_03_25
    logging:
      driver: json-file
      options:
        max-size: "2m"    # Ротация при достижении 10 МБ
        max-file: "3"      # Хранить 3 файла (логи + 2 архива)
    restart: "always"
    volumes:
      - .:/app
      - ./logs:/app_logs  # Монтируем папку для логов
    working_dir: /app
    command: sh -c "python main.py 2>&1 | tee -a /app_logs/script_logs.log"
    environment:
      - PYTHONUNBUFFERED=1