PROJECT_NAME = "#bybit_imbalance_06_07_25"
TABLE_DEALS = "bybittpsl_06_07_25_deals"
TABLE_COINS = "bybittpsl_06_07_25_coins"

DELAY = 60
MAX_COUNT_OF_DEALS = 5
MONEY_FOR_ONE_ORDER = 50
TAKE_PROFIT = 1
STOP_LOSS = 50
DEMO_TRADE = False
ATR_SL = 1.5
ATR_TP = 2
COINS = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "DOTUSDT", "LTCUSDT", "ATOMUSDT",
"APEUSDT", "LINKUSDT", "NEARUSDT", "PEPEUSDT", "SHIBUSDT", "IMXUSDT", "TONUSDT", "SANDUSDT", "XLMUSDT",
"ONDOUSDT", "MNTUSDT", "SWEATUSDT", "TRXUSDT", "DOGSUSDT"]

