name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify secrets availability
      run: |
        echo "List of secrets used in this job:"
        echo "SSH_HOST: ${{ secrets.SSH_HOST != '' && 'SET' || 'NOT SET' }}"
        echo "SSH_USER: ${{ secrets.SSH_USER != '' && 'SET' || 'NOT SET' }}"
        echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY != '' && 'SET' || 'NOT SET' }}"

#    - name: Setup SSH key
#      run: |
#        mkdir -p ~/.ssh
#        chmod 700 ~/.ssh
#        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
#        chmod 600 ~/.ssh/deploy_key
#    - name: Setup SSH
#      run: |
#        mkdir -p ~/.ssh
#        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
#        chmod 600 ~/.ssh/deploy_key
#        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts


#    - name: Debug key format
#      run: |
#        echo "Key content:"
#        cat ~/.ssh/deploy_key | awk '{print "Line "NR": "$0}'

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /scripts/
          docker compose down
          docker compose pull
          docker compose up -d