name: Deploy to VPS

on:
  push:
    branches: [ main, bybit_script_2 ]


permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      BYBIT_DEMO_API_KEY: ${{ secrets.BYBIT_DEMO_API_KEY }}
      BYBIT_DEMO_SECRET_KEY: ${{ secrets.BYBIT_DEMO_SECRET_KEY }}
      #DEPLOY_PATH: scripts/bybit_script

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

#      - name: Run tests
#        run: pytest -s -v --alluredir=allure_results
#        continue-on-error: true

      - name: Run API tests with pytest and generate Allure results  # Запуск тестов
        run: |
          pytest --alluredir=allure-results
        continue-on-error: true

      - name: Upload Allure results  # Загружаем результаты тестов в GitHub Actions
        if: always()  # Загружаем файлы независимо от успеха/неуспеха тестов
        uses: actions/upload-artifact@v4
        with:
          name: allure-results  # Название артефакта
          path: allure-results  # Путь к файлам отчета
          #retention-days: 7

  publish-report:  # Джоба для публикации Allure-отчета на GitHub Pages
    needs: [ run-tests ]  # Выполняется только после успешного выполнения run-tests
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Check out repository  # Клонируем репозиторий, включая ветку gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages  # Операции будем выполнять в ветке gh-pages
          path: gh-pages  # Клонируем файлы в папку gh-pages

      - name: Download Allure results  # Загружаем ранее сохраненные результаты тестов
        uses: actions/download-artifact@v4
        with:
          name: allure-results  # Название артефакта
          path: allure-results  # Путь для скачивания

      - name: Allure Report action from marketplace  # Генерация отчета Allure
        uses: simple-elf/allure-report-action@v1.12
        if: always()
        with:
          allure_results: allure-results  # Папка с результатами тестов
          allure_history: allure-history  # Папка для хранения истории отчетов

      - name: Deploy report to Github Pages  # Публикация отчета на GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Токен для доступа к репозиторию
          publish_branch: gh-pages  # Публикуем отчет в ветку gh-pages
          publish_dir: allure-history  # Папка, где находится сгенерированный отчет

  deploy:
    needs: run-tests  # Запуск деплоя только после успешного прогона тестов
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify secrets availability
      run: |
        echo "List of secrets used in this job:"
        echo "SSH_HOST: ${{ secrets.SSH_HOST != '' && 'SET' || 'NOT SET' }}"
        echo "SSH_USER: ${{ secrets.SSH_USER != '' && 'SET' || 'NOT SET' }}"
        echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY != '' && 'SET' || 'NOT SET' }}"

    - name: Copy files to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22 # Указываем порт для SSH 46952
        source: "."  # Копируем весь репозиторий
        target: "/root/scripts/bybit_script_2" # Указываем папку на сервере /root/${{ env.DEPLOY_PATH }} /root/scripts/bybit_script

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.1.0 #1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22 # Указываем порт для SSH  22 изменил на 46953
        script: |
          cd /root/scripts/bybit_script_2
          docker compose down
          docker system prune -af
          docker compose up -d

    - name: Send Telegram Notification
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="🛠 Деплой проекта успешно завершен!"
